[tool.poetry]
name = "lvm_sandbox"
version = "0.1.0"
description = "Sandbox for LVM scripts and tools."
authors = ["José Sánchez-Gallego <gallegoj@uw.edu>"]

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
astropy = ">=5.0.0"
pandas = "^1.3.1"
numpy = "^1.21.1"
tables = "^3.6.1"
sep = "^1.2.0"
matplotlib = "^3.5"
seaborn = "^0.12.0"
tqdm = "^4.62.3"
rich = "^11.2.0"
pyds9 = "^1.8.1"
sdss-clu = "^1.9.0"

[tool.poetry.dev-dependencies]
ipython = ">=8.0.0"
invoke = "*"
flake8 = "*"
doc8 = ">=0.8.0"
pytest = ">=6.0"
pytest-asyncio = "*"
pytest-cov = "*"
pytest-sugar = "*"
isort = ">=5.0.0"
typing_extensions = {version="*", python="~3.7"}
codecov = ">=2.0.15"
coverage = {version = ">=5.0", extras = ["toml"]}
asynctest = {version=">=0.13.0", python="~3.7"}
asyncmock = {version=">=0.4.2", python="~3.7"}
Sphinx = {version = ">=3.0"}
sphinx-click = {version = ">=2.3.0"}
ipdb = ">=0.13.3"
autopep8 = ">=1.5.4"
black = {version = ">=20.8b1", allow-prereleases = true}
rstcheck = ">=3.3.1"
pytest-mock = ">=3.5.1"
pyserial-asyncio = ">=0.5"
sphinx-jsonschema = ">=1.16.8"
myst-parser = ">=0.14.0"
furo = "^2021.6.18-beta.36"
nox = "^2021.6.12"
sphinx-autobuild = "^2021.3.14"
sphinx-copybutton = "^0.3.3"
pandas-stubs = "^1.2.0"

[tool.black]
line-length = 88
target-version = ['py311']
fast = true

[tool.isort]
profile = "black"
sections = ["FUTURE", "STDLIB", "TYPING", "THIRDPARTY", "SDSS", "FIRSTPARTY", "LOCALFOLDER"]
default_section = "THIRDPARTY"
known_first_party = "lvm_sandbox"
known_typing = ["typing"]
known_sdss = ["sdsstools", "clu", "sdssdb"]
lines_after_imports = 2

[build-system]
requires = ["poetry-core>=1.1.0"]
build-backend = "poetry.core.masonry.api"
