[tool.poetry]
name = "lvm_sandbox"
version = "0.1.0"
description = "Sandbox for LVM scripts and tools."
authors = ["José Sánchez-Gallego <gallegoj@uw.edu>"]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
astropy = ">=5.0.0"
pandas = "^2.0.0"
numpy = "^1.21.1"
tables = "^3.6.1"
sep = "^1.2.0"
matplotlib = "^3.5"
seaborn = "^0.12.0"
sdsstools = "^1.1.0"
lvmguider = { path = "../lvmguider" }

[tool.poetry.dev-dependencies]
ipython = ">=8.0.0"
invoke = "*"
flake8 = "*"
doc8 = ">=0.8.0"
isort = ">=5.0.0"
typing_extensions = {version="*", python="~3.7"}
ipdb = ">=0.13.3"
autopep8 = ">=1.5.4"
black = {version = ">=20.8b1", allow-prereleases = true}
pandas-stubs = ">=2.0.0"

[tool.black]
line-length = 88
target-version = ['py311']
fast = true

[tool.isort]
profile = "black"
sections = ["FUTURE", "STDLIB", "TYPING", "THIRDPARTY", "SDSS", "FIRSTPARTY", "LOCALFOLDER"]
default_section = "THIRDPARTY"
known_first_party = "lvm_sandbox"
known_typing = ["typing"]
known_sdss = ["sdsstools"]
lines_after_imports = 2

[build-system]
requires = ["poetry-core>=1.1.0"]
build-backend = "poetry.core.masonry.api"
